# Generated by Django 3.2.4 on 2021-06-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentBookk',
            new_name='RentBook',
        ),
    ]
